ASP_Meeting_8/Models/ViewModels/CatViewModels/CatsByBreedViewModel.cs
using ASP_Meeting_8.Models.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_Meeting_8.Models.ViewModels.CatViewModels
{
    public class CatsByBreedViewModel
    {
        public IEnumerable<CatDTO> Cats { get; set; } = default!;
        public IEnumerable<BreedDTO> Breeds { get; set; } = default!;

    }
}

ASP_Meeting_8/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP_Meeting_8.Data.Entities;
using ASP_Meeting_8.Models.ViewModels.CatViewModels;
using ASP_Meeting_8.Models.DTO;
using AutoMapper;

namespace ASP_Meeting_8.Controllers
{
    public class CatsController : Controller
    {
        private readonly CatContext _context;
        private readonly IMapper mapper;
        private readonly ILogger _logger;

        public CatsController(CatContext context,
            ILoggerFactory loggerFactory,
            IMapper mapper)
        {
            _context = context;
            this.mapper = mapper;
            _logger = loggerFactory.CreateLogger<CatsController>();
        }

        // GET: Cats
        public async Task<IActionResult> Index(int breedId, string? search)
        {

            IQueryable<Cat> cats = _context.Cats
                .Include(c => c.Breed)
                .Where(t => t.IsDeleted == false);
            if (breedId > 0)
                cats = cats.Where(t => t.BreedId == breedId);
            if (search is not null)
                cats = cats.Where(t => t.CatName.Contains(search));
            IQueryable<Breed> breeds = _context.Breeds;
            SelectList breedSL = new SelectList(await breeds.ToListAsync(),
                dataValueField: nameof(Breed.Id),
                dataTextField: nameof(Breed.BreedName),
                selectedValue: breedId);
            IEnumerable<CatDTO> tempCats = mapper.Map<IEnumerable<CatDTO>>(
                await cats.ToListAsync()
                );
            //var tempCats = await cats
            //    //mapping Cat to CatDTO
            //    .Select(t=>new CatDTO{
            //        Id= t.Id, 
            //        CatName= t.CatName,
            //        Description= t.Description,
            //        IsVacinated = t.IsVacinated,
            //        Gender= t.Gender,
            //        BreedId = t.BreedId,
            //        Image = t.Image,
            //        Breed = new BreedDTO
            //        {
            //            Id = t.Breed.Id,
            //            BreedName= t.Breed.BreedName,
            //        }
            //    })
            //    //
            //    .ToListAsync();
            IndexCatViewModel vM = new IndexCatViewModel
            {
                Cats = tempCats,
                BreedSL = breedSL,
                BreedId = breedId,
                Search = search
            };
            return View(vM);
        }

        // GET: Cats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }

            var cat = await _context.Cats
                .Include(c => c.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cat == null)
            {
                return NotFound();
            }
            DetailsCatViewModel vM = new DetailsCatViewModel
            {
                Cat = mapper.Map<CatDTO>(cat)
            };
            return View(vM);
        }

        // GET: Cats/Create
        public IActionResult Create()
        {
            //ViewData["BreedId"] = new SelectList(_context.Breeds, "Id", "BreedName");
            //ViewData["CatGender"] = new SelectList(Enum.GetValues(typeof(CatGender)));
            CreateCatViewModel vM = new CreateCatViewModel
            {
                BreedSL = new SelectList(_context.Breeds, "Id", "BreedName")
            };
            return View(vM);
        }

        // POST: Cats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,CatName,Description,Gender,IsVacinated,Image,BreedId")] Cat cat)
        public async Task<IActionResult> Create(CreateCatViewModel vM)
        {
            if (!ModelState.IsValid)
            {
                //foreach (var key in ModelState.Keys)
                //    _logger.LogInformation($"Waiting keys: {key}");
                SelectList breedSL = new SelectList(await _context.Breeds.ToListAsync(),
                    nameof(Breed.Id),
                    nameof(Breed.BreedName),
                    vM.Cat.BreedId);
                vM.BreedSL = breedSL;
                foreach (var error in ModelState.Values.SelectMany(t => t.Errors))
                {
                    _logger.LogError(error.ErrorMessage);
                }
                return View(vM);
            }
            //ViewData["BreedId"] = new SelectList(_context.Breeds, "Id", "BreedName", cat.BreedId);
            //byte[]? buff = null;
            using (BinaryReader br = new BinaryReader(vM.Image.OpenReadStream()))
            {
                vM.Cat.Image = br.ReadBytes((int)vM.Image.Length);
            }
            Cat createdCat = mapper.Map<Cat>(vM.Cat);
            _context.Add(createdCat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Cats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            int idForDemonstration = Convert.ToInt32(RouteData.Values["id"]!.ToString());
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }

            var cat = await _context.Cats.FindAsync(id);
            if (cat == null)
            {
                return NotFound();
            }
            if (cat.IsDeleted)
                return Unauthorized();
            IQueryable<Breed> breeds = _context.Breeds;
            SelectList breedSL = new SelectList(await breeds.ToListAsync(),
                nameof(Breed.Id),
                nameof(Breed.BreedName),
                selectedValue: cat.BreedId);
            EditCatViewModel vM = new EditCatViewModel
            {
                BreedSL = breedSL,
                Cat = mapper.Map<CatDTO>(cat)
            };
            return View(vM);
        }

        // POST: Cats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditCatViewModel vM)
        {
            if (id != vM.Cat.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(t => t.Errors))
                    _logger.LogError(error.ErrorMessage);
                IQueryable<Breed> breeds = _context.Breeds;
                SelectList breedSL = new SelectList(await breeds.ToListAsync(),
                    nameof(Breed.Id),
                    nameof(Breed.BreedName),
                    selectedValue: vM.Cat.BreedId);
                vM.BreedSL = breedSL;
                return View(vM);
            }
            try
            {
                if (vM.Image is not null)
                {
                    using (BinaryReader br = new BinaryReader(vM.Image.OpenReadStream()))
                    {
                        vM.Cat.Image = br.ReadBytes((int)vM.Image.Length);
                    }
                }
                Cat editedCat = mapper.Map<Cat>(vM.Cat);
                _context.Update(editedCat);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CatExists(vM.Cat.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Cats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cats == null)
            {
                return NotFound();
            }
            var cat = await _context.Cats
                .Include(c => c.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cat == null)
            {
                return NotFound();
            }
            DeleteCatViewModel vM = new DeleteCatViewModel
            {
                Cat = mapper.Map<CatDTO>(cat)
            };
            return View(vM);
        }

        // POST: Cats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cats == null)
            {
                return Problem("Entity set 'CatContext.Cats'  is null.");
            }
            var cat = await _context.Cats.FindAsync(id);
            if (cat != null)
            {
                //_context.Cats.Remove(cat);
                cat.IsDeleted = true;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CatExists(int id)
        {
            return _context.Cats.Any(e => e.Id == id);
        }

        public async Task<IActionResult> CatsByBreed(string? breed)
        {
            //string? breed = RouteData.Values["breed"].ToString();
            IQueryable<Cat> cats = _context.Cats
               .Include(c => c.Breed)
               .Where(t => t.IsDeleted == false);
            if (breed != null)
                cats = cats.Where(t => t.Breed!.BreedName == breed);

            IEnumerable<CatDTO> tempCats = mapper.Map<IEnumerable<CatDTO>>(

ASP_Meeting_8/Views/Cats/CatsByBreed.cshtml
@addTagHelper *, ASP_Meeting_8
@model CatsByBreedViewModel
@{
    var routeData = Context.GetRouteData();
    string? currentPage = routeData.Values["breed"]?.ToString();
}

<div class="row">
        @*<div>
            @foreach (BreedDTO breed in Model.Breeds)
            {
                <div class="col">
                    <a asp-controller="Cats" asp-action="CatsByBreed" asp-route-breed="@breed.BreedName">@breed.BreedName</a>
                </div>
            }
            <a asp-controller="Cats" asp-action="CatsByBreed" asp-route-breed="">All</a>
        </div>*@
    <cats-by-breed asp-action="CatsByBreed" asp-controller="Cats" breeds="@Model.Breeds" current-page="@currentPage"></cats-by-breed>
        @foreach (CatDTO cat in Model.Cats)
        {
            <div class="col col-xl-3 col-lg-4 col-md-6 col-12 mb-5">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@cat.CatName</h5>
                        <p class="card-text text-truncate">@cat.Description</p>
                        <p class="card-text">
                            <small class="text-muted">
                                @Html.DisplayNameFor(model=> model.Cats.First().Breed!.BreedName) :
                                @cat.Breed?.BreedName
                            </small>
                        </p>
                    </div>
                    <div class="btn-group btn-group-sm mb-2">
                        <a asp-action="Details"
                       asp-route-id="@cat.Id"
                       class="btn btn-outline-success">Details</a>
                        <a asp-action="Edit"
                       asp-route-id="@cat.Id"
                       class="btn btn-outline-warning">Edit</a>
                        <a asp-action="Delete"
                       asp-route-id="@cat.Id"
                       class="btn btn-outline-danger">Delete</a>
                    </div>
                    <img src="data:image/*;base64,@(Convert.ToBase64String(cat.Image!))" class="card-img-bottom" alt="@cat.CatName">
                </div>
            </div>
        }
</div>

ASP_Meeting_8/Views/Cats/Create _old.cshtml
@using ASP_Meeting_8.Models.DTO
@model ASP_Meeting_8.Data.Entities.Cat

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CatName" class="control-label"></label>
                <input asp-for="CatName" class="form-control" />
                <span asp-validation-for="CatName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control" 
                asp-items="@new SelectList(Enum.GetValues(typeof(CatGender)))"
                ></select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVacinated" /> @Html.DisplayNameFor(model => model.IsVacinated)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" id="Image" name="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
           @* <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>*@
            <div class="form-group">
                <label asp-for="BreedId" class="control-label"></label>
                <select asp-for="BreedId" class ="form-control" asp-items="ViewBag.BreedId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ASP_Meeting_8/Views/Cats/Create.cshtml
@model CreateCatViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cat.CatName" class="control-label"></label>
                <input asp-for="Cat.CatName" class="form-control" />
                <span asp-validation-for="Cat.CatName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cat.Description" class="control-label"></label>
                <input asp-for="Cat.Description" class="form-control" />
                <span asp-validation-for="Cat.Description" class="text-danger"></span>
            </div>
            <div class="form-group">@Html.DisplayNameFor(model=>model.Cat.Gender)<br />
                @*<label asp-for="Cat.Gender" class="control-label"></label>
                <select asp-for="Cat.Gender" class="form-control" 
                asp-items="@new SelectList(Enum.GetValues(typeof(CatGender)))"
                ></select>
                <span asp-validation-for="Cat.Gender" class="text-danger"></span>*@
                
                    @foreach (var gender in Enum.GetValues(typeof(CatGender))){
                    <div class="form-check">
                        <input asp-for="Cat.Gender"
                            type="radio"
                            value="@gender"
                            class="form-check-input">
                            <label asp-for="Cat.Gender"
                            class="form-check-label">@gender</label>
                    </div>
                    }
               
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Cat.IsVacinated" /> @Html.DisplayNameFor(model => model.Cat.IsVacinated)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" id="Image" name="Image" class="form-control" 
                accept="image/*"/>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cat.Breed" class="control-label"></label>
                <select asp-for="Cat.BreedId" class ="form-control" asp-items="@Model.BreedSL"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ASP_Meeting_8/Views/Cats/Delete.cshtml
@model DeleteCatViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.CatName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.CatName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.IsVacinated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.IsVacinated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="data:image/*;base64,@(Convert.ToBase64String(Model.Cat.Image!))"
                 alt="@Model.Cat.CatName"
            class="w-25" />
        </dd>
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Breed!.BreedName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Cat.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP_Meeting_8/Views/Cats/Details.cshtml
@model DetailsCatViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.CatName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.CatName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.IsVacinated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.IsVacinated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Image)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.Breed!.BreedName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Cat.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP_Meeting_8/Views/Cats/Edit.cshtml
@model EditCatViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Cat.Id" />
            <input type="hidden" asp-for="Cat.Image" />
            <div class="form-group">
                <label asp-for="Cat.CatName" class="control-label"></label>
                <input asp-for="Cat.CatName" class="form-control" />
                <span asp-validation-for="Cat.CatName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cat.Description" class="control-label"></label>
                <input asp-for="Cat.Description" class="form-control" />
                <span asp-validation-for="Cat.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model=>model.Cat.Gender)<br />
                

                @foreach (var gender in Enum.GetValues(typeof(CatGender)))
                {
                    <div class="form-check">
                        <input asp-for="Cat.Gender"
                           type="radio"
                           value="@gender"
                           class="form-check-input">
                        <label asp-for="Cat.Gender"
                           class="form-check-label">@gender</label>
                    </div>
                }

            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Cat.IsVacinated" />
                    @Html.DisplayNameFor(model => model.Cat.IsVacinated)
                </label>
            </div>
            <div class="form-group">
                <div class="mb-3">Current Image:<br />
                    <img src="data:image/*;base64,@(Convert.ToBase64String(Model.Cat.Image!))" 
                    class="card-img-bottom w-100" alt="@Model.Cat.CatName" />
                </div>
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image"  
                type="file"
                accept="image/*"
                class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cat.BreedId" class="control-label"></label>
                <select asp-for="Cat.BreedId" class="form-control" asp-items="@Model.BreedSL"></select>
                <span asp-validation-for="Cat.BreedId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP_Meeting_8/Views/Cats/Index.cshtml
@model IndexCatViewModel

@{
    ViewData["Title"] = "Index";
    ViewData["Author"] = "Serhii Ruban";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    @Html.ActionLink("Додати кота", "Create", routeValues: null, htmlAttributes: new {@class="btn btn-sm btn-warning", id="createBtn"})
</p>
<form asp-action="Index" method="get">
    <div class="row mb-5">
        <div class="col col-md-4 col-12">
            <select asp-for="BreedId"
                    class="form-select bg-light text-dark"
                    asp-items="@Model.BreedSL">
                <option value="0">All</option>
            </select>
           
        </div>
        <div class="col col-md-4 col-12">
        @Html.DropDownList("days", new SelectList(new[] {"monday", "tuesday", "wednesday"}), new {@class="form-select"} )
        </div>
      @*  <div class="col col-md-4 col-12">
            <input type="text"
                   asp-for="Search"
                   placeholder="Search in cat name..."
                   class="form-control" />
        </div>*@
        <div class="col col-md-4 col-12">
            <button type="submit" class="btn btn-outline-success">Seacrh</button>
        </div>
    </div>
</form>
<div class="row">
    @foreach (CatDTO cat in Model.Cats)
    {
        <div class="col col-xl-3 col-lg-4 col-md-6 col-12 mb-5">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@cat.CatName</h5>
                    <p class="card-text text-truncate">@cat.Description</p>
                    <p class="card-text">
                        <small class="text-muted">
                            @Html.DisplayNameFor(model=> model.Cats.First().Breed!.BreedName) :
                            @cat.Breed?.BreedName
                        </small>
                    </p>
                </div>
                <div class="btn-group btn-group-sm mb-2">
                    <a asp-action="Details"
                    asp-route-id="@cat.Id"
                    class="btn btn-outline-success">Details</a>
                    <a asp-action="Edit"
                   asp-route-id="@cat.Id"
                   class="btn btn-outline-warning">Edit</a>
                    <a asp-action="Delete"
                   asp-route-id="@cat.Id"
                   class="btn btn-outline-danger">Delete</a>
                </div>
                <img src="data:image/*;base64,@(Convert.ToBase64String(cat.Image!))" class="card-img-bottom" alt="@cat.CatName">
            </div>
        </div>
    }
</div>